"""Regenerate migration after reset

Revision ID: 9f001730834f
Revises: 82446c8a38e8
Create Date: 2025-05-16 16:07:59.829949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f001730834f'
down_revision = '82446c8a38e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_data',
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_data')
    op.drop_table('notification')
    op.drop_table('friend')
    # ### end Alembic commands ###
