"""Add timestamp column to Notification

Revision ID: ba4815fc68fe
Revises: eca1eeb1dba7
Create Date: 2025-05-16 12:07:26.960402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4815fc68fe'
down_revision = 'eca1eeb1dba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
