"""Add image_data column to charts

Revision ID: bcde46192639
Revises: 08aa703e124d
Create Date: 2025-05-13 12:07:07.435315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcde46192639'
down_revision = '08aa703e124d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
