"""Replace image_data with image_path in charts

Revision ID: cb6da990bc77
Revises: bcde46192639
Create Date: 2025-05-15 11:40:15.171301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6da990bc77'
down_revision = 'bcde46192639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.TEXT(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
