"""Add is_imported column

Revision ID: fc087c6b6e66
Revises: ef685f9036cf
Create Date: 2025-05-16 22:25:09.859606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc087c6b6e66'
down_revision = 'ef685f9036cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_imported', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_column('is_imported')

    # ### end Alembic commands ###
